/**
 * Copy the bundled font files out of node_modules and into src/lib/signature/fonts/.
 *
 * The fonts are committed rather than resolved at build time. Three reasons: the
 * build must work from a clean checkout with no network, the file that ships is
 * then the file you can read in the repo, and the OFL requires the licence to
 * travel with the font — which only happens reliably if both are versioned
 * together.
 *
 * `.ttf` specifically, not `.woff2`: opentype.js cannot parse woff2, and the
 * whole point of this app is that the signature becomes outlines rather than
 * text that needs a font to render.
 *
 * Run with `npm run fonts:vendor` after adding a face to FACES.
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const OUT = fileURLToPath(new URL('../src/lib/signature/fonts/', import.meta.url));
const MODULES = fileURLToPath(new URL('../node_modules/', import.meta.url));

/** Every bundled face, with where its `.ttf` and its licence come from. */
const FACES = [
  { id: 'dancing-script', name: 'Dancing Script', slug: 'DancingScript' },
  { id: 'great-vibes', name: 'Great Vibes', slug: 'GreatVibes' },
  { id: 'sacramento', name: 'Sacramento', slug: 'Sacramento' },
  { id: 'caveat', name: 'Caveat', slug: 'Caveat' },
  { id: 'allura', name: 'Allura', slug: 'Allura' },
  { id: 'parisienne', name: 'Parisienne', slug: 'Parisienne' },
  { id: 'mr-de-haviland', name: 'Mr De Haviland', slug: 'MrDeHaviland' },
].map((f) => ({
  ...f,
  pkg: `@expo-google-fonts/${f.id}`,
  ttf: `400Regular/${f.slug}_400Regular.ttf`,
  file: `${f.slug}-Regular.ttf`,
}));

mkdirSync(OUT, { recursive: true });

/** Collected as we go, then written out as fonts/README.md. */
const provenance = [];

for (const face of FACES) {
  const from = `${MODULES}${face.pkg}/${face.ttf}`;
  if (!existsSync(from)) throw new Error(`${face.name}: no ttf at ${from} — is ${face.pkg} installed?`);

  copyFileSync(from, `${OUT}${face.file}`);

  // The licence has to be the one shipped with this exact copy of the font.
  // A licence fetched from somewhere else is a claim about the file, not a
  // licence for it.
  //
  // LICENSE_FONT before LICENSE: these packages carry two licences, MIT for the
  // wrapper code and the OFL for the font. Reading the wrong one would attach a
  // licence to the .ttf that does not govern it.
  const licence = ['OFL.txt', 'LICENSE_FONT', 'LICENSE', 'LICENSE.txt']
    .map((f) => `${MODULES}${face.pkg}/${f}`)
    .find((f) => existsSync(f));
  if (!licence) throw new Error(`${face.name}: ${face.pkg} ships no licence file — do not bundle it`);

  const text = readFileSync(licence, 'utf8');
  if (!/SIL OPEN FONT LICENSE/i.test(text)) {
    throw new Error(`${face.name}: licence at ${licence} is not the SIL OFL — do not bundle it`);
  }
  writeFileSync(`${OUT}${face.file.replace(/\.ttf$/, '.OFL.txt')}`, text);

  const meta = JSON.parse(readFileSync(`${MODULES}${face.pkg}/package.json`, 'utf8'));
  const upstream = existsSync(`${MODULES}${face.pkg}/metadata.json`)
    ? JSON.parse(readFileSync(`${MODULES}${face.pkg}/metadata.json`, 'utf8'))
    : {};

  provenance.push({
    name: face.name,
    file: face.file,
    licenceFile: face.file.replace(/\.ttf$/, '.OFL.txt'),
    pkg: `${face.pkg}@${meta.version ?? 'unknown'}`,
    upstreamVersion: upstream.version ?? 'unknown',
    subsets: upstream.subsets ?? [],
  });

  console.log(`${face.name} → ${face.file}`);
}

// Written next to the fonts so the repo answers "where did this .ttf come from"
// without anyone having to reinstall node_modules to find out.
writeFileSync(
  `${OUT}README.md`,
  `# Bundled fonts

Generated by \`npm run fonts:vendor\` — do not edit by hand.

Every face here is licensed under the SIL Open Font License 1.1, and its licence
text sits beside it under the same name. The \`.ttf\` is copied verbatim out of the
npm package named below; nothing is subset or re-encoded.

${provenance
  .map(
    (f) =>
      `## ${f.name}\n\n` +
      `- File: \`${f.file}\`\n` +
      `- Licence: \`${f.licenceFile}\` (OFL-1.1)\n` +
      `- Source package: \`${f.pkg}\`\n` +
      `- Upstream version: ${f.upstreamVersion}\n` +
      `- Subsets: ${f.subsets.join(', ') || 'unknown'}\n`,
  )
  .join('\n')}`,
);
