/**
 * Copy the bundled font files out of node_modules and into src/lib/signature/fonts/.
 *
 * The fonts are committed rather than resolved at build time. Three reasons: the
 * build must work from a clean checkout with no network, the file that ships is
 * then the file you can read in the repo, and the OFL requires the licence to
 * travel with the font — which only happens reliably if both are versioned
 * together.
 *
 * `.ttf` specifically, not `.woff2`: opentype.js cannot parse woff2, and the
 * whole point of this app is that the signature becomes outlines rather than
 * text that needs a font to render.
 *
 * Run with `npm run fonts:vendor` after adding a face to FACES.
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import subsetFont from 'subset-font';

const OUT = fileURLToPath(new URL('../src/lib/signature/fonts/', import.meta.url));
const TEXT_OUT = fileURLToPath(
  new URL('../src/lib/document/certificate/appearance/fonts/', import.meta.url),
);
const MODULES = fileURLToPath(new URL('../node_modules/', import.meta.url));

/** Every bundled face, with where its `.ttf` and its licence come from. */
const FACES = [
  { id: 'dancing-script', name: 'Dancing Script', slug: 'DancingScript' },
  { id: 'great-vibes', name: 'Great Vibes', slug: 'GreatVibes' },
  { id: 'sacramento', name: 'Sacramento', slug: 'Sacramento' },
  { id: 'caveat', name: 'Caveat', slug: 'Caveat' },
  { id: 'allura', name: 'Allura', slug: 'Allura' },
  { id: 'parisienne', name: 'Parisienne', slug: 'Parisienne' },
  { id: 'mr-de-haviland', name: 'Mr De Haviland', slug: 'MrDeHaviland' },
].map((f) => ({
  ...f,
  pkg: `@expo-google-fonts/${f.id}`,
  ttf: `400Regular/${f.slug}_400Regular.ttf`,
  file: `${f.slug}-Regular.ttf`,
}));

mkdirSync(OUT, { recursive: true });

/** Collected as we go, then written out as fonts/README.md. */
const provenance = [];

for (const face of FACES) {
  const from = `${MODULES}${face.pkg}/${face.ttf}`;
  if (!existsSync(from)) throw new Error(`${face.name}: no ttf at ${from} — is ${face.pkg} installed?`);

  copyFileSync(from, `${OUT}${face.file}`);

  // The licence has to be the one shipped with this exact copy of the font.
  // A licence fetched from somewhere else is a claim about the file, not a
  // licence for it.
  //
  // LICENSE_FONT before LICENSE: these packages carry two licences, MIT for the
  // wrapper code and the OFL for the font. Reading the wrong one would attach a
  // licence to the .ttf that does not govern it.
  const licence = ['OFL.txt', 'LICENSE_FONT', 'LICENSE', 'LICENSE.txt']
    .map((f) => `${MODULES}${face.pkg}/${f}`)
    .find((f) => existsSync(f));
  if (!licence) throw new Error(`${face.name}: ${face.pkg} ships no licence file — do not bundle it`);

  const text = readFileSync(licence, 'utf8');
  if (!/SIL OPEN FONT LICENSE/i.test(text)) {
    throw new Error(`${face.name}: licence at ${licence} is not the SIL OFL — do not bundle it`);
  }
  writeFileSync(`${OUT}${face.file.replace(/\.ttf$/, '.OFL.txt')}`, text);

  const meta = JSON.parse(readFileSync(`${MODULES}${face.pkg}/package.json`, 'utf8'));
  const upstream = existsSync(`${MODULES}${face.pkg}/metadata.json`)
    ? JSON.parse(readFileSync(`${MODULES}${face.pkg}/metadata.json`, 'utf8'))
    : {};

  provenance.push({
    name: face.name,
    file: face.file,
    licenceFile: face.file.replace(/\.ttf$/, '.OFL.txt'),
    pkg: `${face.pkg}@${meta.version ?? 'unknown'}`,
    upstreamVersion: upstream.version ?? 'unknown',
    subsets: upstream.subsets ?? [],
  });

  console.log(`${face.name} → ${face.file}`);
}

// Written next to the fonts so the repo answers "where did this .ttf come from"
// without anyone having to reinstall node_modules to find out.
writeFileSync(
  `${OUT}README.md`,
  `# Bundled fonts

Generated by \`npm run fonts:vendor\` — do not edit by hand.

Every face here is licensed under the SIL Open Font License 1.1, and its licence
text sits beside it under the same name. The \`.ttf\` is copied verbatim out of the
npm package named below; nothing is subset or re-encoded.

${provenance
  .map(
    (f) =>
      `## ${f.name}\n\n` +
      `- File: \`${f.file}\`\n` +
      `- Licence: \`${f.licenceFile}\` (OFL-1.1)\n` +
      `- Source package: \`${f.pkg}\`\n` +
      `- Upstream version: ${f.upstreamVersion}\n` +
      `- Subsets: ${f.subsets.join(', ') || 'unknown'}\n`,
  )
  .join('\n')}`,
);

// ---------------------------------------------------------------------------
// The text face, for the details block beside a visible signature.
//
// Not a handwriting face and not offered as one: it is the app's own UI font,
// drawn into a PDF as outlines the same way a signature is. Kept in its own
// directory so that nothing enumerating the signature faces can pick it up.
//
// Subset, which is the one place this script departs from copying verbatim.
// The reason is the audience: the built-in PDF fonts are WinAnsi, which turns
// "Jiří Novák" into "Ji?í Novák", and the certificates this feature exists for
// are Czech. Latin Extended-A is what fixes that, and carrying the other 2,000
// glyphs to get it would cost 342 kB instead of 93 kB.

const TEXT_FACE = {
  name: 'Inter',
  pkg: '@expo-google-fonts/inter',
  ttf: '400Regular/Inter_400Regular.ttf',
  file: 'Inter-Regular-Latin.ttf',
};

/**
 * Basic Latin, Latin-1 Supplement and Latin Extended-A, plus the punctuation a
 * reason or a location is likely to contain.
 *
 * That covers Czech, Slovak, Polish, Hungarian, the Baltic languages, Turkish
 * and Western Europe. A character outside it is reported to the reader by
 * `unsupportedCharacters`, exactly as it is for a signature face.
 */
function latinCharacters() {
  let characters = '';
  for (let code = 0x20; code <= 0x7e; code += 1) characters += String.fromCharCode(code);
  for (let code = 0xa0; code <= 0xff; code += 1) characters += String.fromCharCode(code);
  for (let code = 0x100; code <= 0x17f; code += 1) characters += String.fromCharCode(code);
  return characters + '\u2018\u2019\u201c\u201d\u2013\u2014\u2026\u20ac';
}

mkdirSync(TEXT_OUT, { recursive: true });

const textFrom = `${MODULES}${TEXT_FACE.pkg}/${TEXT_FACE.ttf}`;
if (!existsSync(textFrom)) {
  throw new Error(`${TEXT_FACE.name}: no ttf at ${textFrom} — is ${TEXT_FACE.pkg} installed?`);
}

const textLicence = ['OFL.txt', 'LICENSE_FONT', 'LICENSE', 'LICENSE.txt']
  .map((f) => `${MODULES}${TEXT_FACE.pkg}/${f}`)
  .find((f) => existsSync(f));
if (!textLicence) {
  throw new Error(`${TEXT_FACE.name}: ${TEXT_FACE.pkg} ships no licence file — do not bundle it`);
}

const textLicenceText = readFileSync(textLicence, 'utf8');
if (!/SIL OPEN FONT LICENSE/i.test(textLicenceText)) {
  throw new Error(`${TEXT_FACE.name}: licence at ${textLicence} is not the SIL OFL — do not bundle it`);
}

const full = readFileSync(textFrom);
const subset = await subsetFont(full, latinCharacters(), { targetFormat: 'truetype' });
writeFileSync(`${TEXT_OUT}${TEXT_FACE.file}`, subset);
writeFileSync(`${TEXT_OUT}${TEXT_FACE.file.replace(/\.ttf$/, '.OFL.txt')}`, textLicenceText);

const textMeta = JSON.parse(readFileSync(`${MODULES}${TEXT_FACE.pkg}/package.json`, 'utf8'));

writeFileSync(
  `${TEXT_OUT}README.md`,
  `# The appearance block's text face

Generated by \`npm run fonts:vendor\` — do not edit by hand.

\`${TEXT_FACE.file}\` is Inter, subset to Basic Latin, Latin-1 Supplement and
Latin Extended-A. It is **not** a signature face and is not offered as one: it
draws the details block beside a visible certificate signature, as outlines,
the same way a signature is drawn.

It is subset rather than copied verbatim — the only font here that is. PDF's
built-in fonts are WinAnsi, which cannot spell a Czech name, and the
certificates this feature exists for are Czech. Latin Extended-A fixes that;
shipping the whole face to get it would cost ${Math.round(full.length / 1024)} kB instead of ${Math.round(subset.length / 1024)} kB.

- Licence: \`${TEXT_FACE.file.replace(/\.ttf$/, '.OFL.txt')}\` (OFL-1.1)
- Source package: \`${TEXT_FACE.pkg}@${textMeta.version ?? 'unknown'}\`
- Full face: ${full.length.toLocaleString()} bytes → subset: ${subset.length.toLocaleString()} bytes
`,
);

console.log(`${TEXT_FACE.name} → ${TEXT_FACE.file} (subset, ${subset.length} bytes)`);
