/**
 * Copy the bundled font files out of node_modules and into src/lib/signature/fonts/.
 *
 * The fonts are committed rather than resolved at build time. Three reasons: the
 * build must work from a clean checkout with no network, the file that ships is
 * then the file you can read in the repo, and the OFL requires the licence to
 * travel with the font — which only happens reliably if both are versioned
 * together.
 *
 * `.ttf` specifically, not `.woff2`: opentype.js cannot parse woff2, and the
 * whole point of this app is that the signature becomes outlines rather than
 * text that needs a font to render.
 *
 * Run with `npm run fonts:vendor` after adding a face to FACES.
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import subsetFont from 'subset-font';

const OUT = fileURLToPath(new URL('../src/lib/signature/fonts/', import.meta.url));
const TEXT_OUT = fileURLToPath(new URL('../src/lib/document/fonts/', import.meta.url));
const MODULES = fileURLToPath(new URL('../node_modules/', import.meta.url));

/** Every bundled face, with where its `.ttf` and its licence come from. */
const FACES = [
  { id: 'dancing-script', name: 'Dancing Script', slug: 'DancingScript' },
  { id: 'great-vibes', name: 'Great Vibes', slug: 'GreatVibes' },
  { id: 'sacramento', name: 'Sacramento', slug: 'Sacramento' },
  { id: 'caveat', name: 'Caveat', slug: 'Caveat' },
  { id: 'allura', name: 'Allura', slug: 'Allura' },
  { id: 'parisienne', name: 'Parisienne', slug: 'Parisienne' },
  { id: 'mr-de-haviland', name: 'Mr De Haviland', slug: 'MrDeHaviland' },
].map((f) => ({
  ...f,
  pkg: `@expo-google-fonts/${f.id}`,
  ttf: `400Regular/${f.slug}_400Regular.ttf`,
  file: `${f.slug}-Regular.ttf`,
}));

mkdirSync(OUT, { recursive: true });

/** Collected as we go, then written out as fonts/README.md. */
const provenance = [];

for (const face of FACES) {
  const from = `${MODULES}${face.pkg}/${face.ttf}`;
  if (!existsSync(from)) throw new Error(`${face.name}: no ttf at ${from} — is ${face.pkg} installed?`);

  copyFileSync(from, `${OUT}${face.file}`);

  // The licence has to be the one shipped with this exact copy of the font.
  // A licence fetched from somewhere else is a claim about the file, not a
  // licence for it.
  //
  // LICENSE_FONT before LICENSE: these packages carry two licences, MIT for the
  // wrapper code and the OFL for the font. Reading the wrong one would attach a
  // licence to the .ttf that does not govern it.
  const licence = ['OFL.txt', 'LICENSE_FONT', 'LICENSE', 'LICENSE.txt']
    .map((f) => `${MODULES}${face.pkg}/${f}`)
    .find((f) => existsSync(f));
  if (!licence) throw new Error(`${face.name}: ${face.pkg} ships no licence file — do not bundle it`);

  const text = readFileSync(licence, 'utf8');
  if (!/SIL OPEN FONT LICENSE/i.test(text)) {
    throw new Error(`${face.name}: licence at ${licence} is not the SIL OFL — do not bundle it`);
  }
  writeFileSync(`${OUT}${face.file.replace(/\.ttf$/, '.OFL.txt')}`, text);

  const meta = JSON.parse(readFileSync(`${MODULES}${face.pkg}/package.json`, 'utf8'));
  const upstream = existsSync(`${MODULES}${face.pkg}/metadata.json`)
    ? JSON.parse(readFileSync(`${MODULES}${face.pkg}/metadata.json`, 'utf8'))
    : {};

  provenance.push({
    name: face.name,
    file: face.file,
    licenceFile: face.file.replace(/\.ttf$/, '.OFL.txt'),
    pkg: `${face.pkg}@${meta.version ?? 'unknown'}`,
    upstreamVersion: upstream.version ?? 'unknown',
    subsets: upstream.subsets ?? [],
  });

  console.log(`${face.name} → ${face.file}`);
}

// Written next to the fonts so the repo answers "where did this .ttf come from"
// without anyone having to reinstall node_modules to find out.
writeFileSync(
  `${OUT}README.md`,
  `# Bundled fonts

Generated by \`npm run fonts:vendor\` — do not edit by hand.

Every face here is licensed under the SIL Open Font License 1.1, and its licence
text sits beside it under the same name. The \`.ttf\` is copied verbatim out of the
npm package named below; nothing is subset or re-encoded.

${provenance
  .map(
    (f) =>
      `## ${f.name}\n\n` +
      `- File: \`${f.file}\`\n` +
      `- Licence: \`${f.licenceFile}\` (OFL-1.1)\n` +
      `- Source package: \`${f.pkg}\`\n` +
      `- Upstream version: ${f.upstreamVersion}\n` +
      `- Subsets: ${f.subsets.join(', ') || 'unknown'}\n`,
  )
  .join('\n')}`,
);

// ---------------------------------------------------------------------------
// The text faces, for documents this app sets itself.
//
// Not handwriting and not offered as such: these draw the details block beside
// a visible signature, and the PDFs the app lays out from `.txt` and `.md`.
// They live in their own directory so nothing enumerating the signature faces
// can reach them.
//
// Subset, which is where this script departs from copying verbatim. The reason
// is the audience: PDF's built-in fonts are WinAnsi, which turns "Uzavřená"
// into "Uzav?ená" — silently, in the body of somebody's document — and the
// languages this app is used in need Latin Extended-A. Carrying the other two
// thousand glyphs to get it would cost four times as much.

const TEXT_FACES = [
  { name: 'Inter', pkg: '@expo-google-fonts/inter', ttf: '400Regular/Inter_400Regular.ttf', file: 'Inter-Regular-Latin.ttf' },
  { name: 'Inter Bold', pkg: '@expo-google-fonts/inter', ttf: '700Bold/Inter_700Bold.ttf', file: 'Inter-Bold-Latin.ttf' },
  { name: 'Inter Italic', pkg: '@expo-google-fonts/inter', ttf: '400Regular_Italic/Inter_400Regular_Italic.ttf', file: 'Inter-Italic-Latin.ttf' },
  { name: 'Inter Bold Italic', pkg: '@expo-google-fonts/inter', ttf: '700Bold_Italic/Inter_700Bold_Italic.ttf', file: 'Inter-BoldItalic-Latin.ttf' },
  { name: 'JetBrains Mono', pkg: '@expo-google-fonts/jetbrains-mono', ttf: '400Regular/JetBrainsMono_400Regular.ttf', file: 'JetBrainsMono-Regular-Latin.ttf' },
];

/**
 * Basic Latin, Latin-1 Supplement and Latin Extended-A, plus the punctuation a
 * document is likely to contain.
 *
 * That covers Czech, Slovak, Polish, Hungarian, the Baltic languages, Turkish
 * and Western Europe. A character outside it is reported to the reader rather
 * than silently replaced.
 */
function latinCharacters() {
  let characters = '';
  for (let code = 0x20; code <= 0x7e; code += 1) characters += String.fromCharCode(code);
  for (let code = 0xa0; code <= 0xff; code += 1) characters += String.fromCharCode(code);
  for (let code = 0x100; code <= 0x17f; code += 1) characters += String.fromCharCode(code);
  return characters + '\u2018\u2019\u201c\u201d\u2013\u2014\u2026\u20ac\u2022\u2192';
}

mkdirSync(TEXT_OUT, { recursive: true });
const textProvenance = [];

for (const face of TEXT_FACES) {
  const from = `${MODULES}${face.pkg}/${face.ttf}`;
  if (!existsSync(from)) throw new Error(`${face.name}: no ttf at ${from} — is ${face.pkg} installed?`);

  const licencePath = ['OFL.txt', 'LICENSE_FONT', 'LICENSE', 'LICENSE.txt']
    .map((f) => `${MODULES}${face.pkg}/${f}`)
    .find((f) => existsSync(f));
  if (!licencePath) throw new Error(`${face.name}: ${face.pkg} ships no licence file — do not bundle it`);

  const licenceText = readFileSync(licencePath, 'utf8');
  if (!/SIL OPEN FONT LICENSE/i.test(licenceText)) {
    throw new Error(`${face.name}: licence at ${licencePath} is not the SIL OFL — do not bundle it`);
  }

  const full = readFileSync(from);
  const subset = await subsetFont(full, latinCharacters(), { targetFormat: 'truetype' });
  writeFileSync(`${TEXT_OUT}${face.file}`, subset);
  writeFileSync(`${TEXT_OUT}${face.file.replace(/\.ttf$/, '.OFL.txt')}`, licenceText);

  const meta = JSON.parse(readFileSync(`${MODULES}${face.pkg}/package.json`, 'utf8'));
  textProvenance.push({ ...face, full: full.length, subset: subset.length, version: meta.version ?? 'unknown' });
  console.log(`${face.name} → ${face.file} (subset, ${subset.length} bytes)`);
}

writeFileSync(
  `${TEXT_OUT}README.md`,
  `# Text faces

Generated by \`npm run fonts:vendor\` — do not edit by hand.

These are **not** signature faces and are not offered as such. They set the
details block beside a visible certificate signature, and the PDFs this app
lays out from \`.txt\` and \`.md\`.

They are the only bundled fonts that are subset rather than copied verbatim.
PDF's built-in fonts are WinAnsi, which cannot spell a Czech, Polish or
Hungarian word — it writes \`?\` instead, silently, in the body of somebody's
document. Latin Extended-A fixes that; shipping the whole faces to get it would
cost four times as much. None of these faces declares a Reserved Font Name, so
the OFL permits subsetting them without renaming.

${textProvenance
  .map(
    (f) =>
      `## ${f.name}\n\n` +
      `- File: \`${f.file}\`\n` +
      `- Licence: \`${f.file.replace(/\.ttf$/, '.OFL.txt')}\` (OFL-1.1)\n` +
      `- Source package: \`${f.pkg}@${f.version}\`\n` +
      `- Full face: ${f.full.toLocaleString()} bytes → subset: ${f.subset.toLocaleString()} bytes\n`,
  )
  .join('\n')}`,
);
