/**
 * Key files made by the test suite, so that none has to be committed.
 *
 * Every other fixture in this project is a captured artefact — a real reply
 * from a real authority, committed because parsing somebody's actual output is
 * the only test worth having. Key material is the exception, and it has to be:
 * a `.p12` carries a private key, this repository is public, and `.gitignore`
 * refuses the extension outright. So these are built when the tests run and
 * exist only in memory.
 *
 * The cost is that the suite cannot test against the file that prompted all of
 * this — a real PostSignum export, whose password is its owner's. What it can
 * do is reproduce that file's **encryption profile** exactly, which is what the
 * reader actually branches on: 3DES for the key, SHA-1 for the MAC. The
 * certificates in a PostSignum file are wrapped in RC2-40, which node-forge can
 * read but cannot write, so that one layer is exercised by
 * `scripts/check-key-file.ts` against a real file instead. The app has no
 * branch of its own there — it hands the container to the fallback whole — so
 * what is left untested by the suite is the fallback's code, not this app's.
 */
import forge from 'node-forge';

export interface KeyFileSet {
  /** PBES2 and AES-256: what a current OpenSSL writes. */
  readonly modern: Uint8Array;
  /** 3DES, as a certificate authority's export still does. */
  readonly legacy: Uint8Array;
  /** The same certificate and key as PEM text. */
  readonly pem: string;
  /** Certificate only, with no key beside it. */
  readonly certificateOnlyPem: string;
  readonly password: string;
  readonly commonName: string;
}

export interface KeyFileOptions {
  readonly commonName?: string;
  readonly password?: string;
  /** Defaults to a certificate that is currently valid. */
  readonly notBefore?: Date;
  readonly notAfter?: Date;
}

const toBinary = (bytes: Uint8Array): string => {
  let out = '';
  for (const byte of bytes) out += String.fromCharCode(byte);
  return out;
};

const fromBinary = (binary: string): Uint8Array =>
  Uint8Array.from(binary, (character) => character.charCodeAt(0));

/**
 * Build a matching set of key files around one freshly generated key.
 *
 * The key is generated by WebCrypto rather than by forge: it is the same
 * algorithm either way, and WebCrypto does it natively in a fraction of the
 * time, which matters when it happens on every test run.
 */
export async function makeKeyFiles(options: KeyFileOptions = {}): Promise<KeyFileSet> {
  const commonName = options.commonName ?? 'Fixture Signer';
  const password = options.password ?? 'test123';

  const pair = await crypto.subtle.generateKey(
    {
      name: 'RSASSA-PKCS1-v1_5',
      modulusLength: 2048,
      publicExponent: new Uint8Array([0x01, 0x00, 0x01]),
      hash: 'SHA-256',
    },
    true,
    ['sign', 'verify'],
  );

  const pkcs8 = new Uint8Array(await crypto.subtle.exportKey('pkcs8', pair.privateKey));
  const privateKey = forge.pki.privateKeyFromAsn1(
    forge.asn1.fromDer(forge.util.createBuffer(toBinary(pkcs8))),
  ) as forge.pki.rsa.PrivateKey;

  const certificate = forge.pki.createCertificate();
  certificate.publicKey = forge.pki.setRsaPublicKey(privateKey.n, privateKey.e);
  certificate.serialNumber = '01';
  certificate.validity.notBefore = options.notBefore ?? new Date(Date.UTC(2020, 0, 1));
  certificate.validity.notAfter = options.notAfter ?? new Date(Date.UTC(2039, 0, 1));

  const name = [
    { name: 'commonName', value: commonName },
    { name: 'organizationName', value: 'xSignature' },
    { name: 'countryName', value: 'CZ' },
  ];
  certificate.setSubject(name);
  certificate.setIssuer(name);
  certificate.sign(privateKey, forge.md.sha256.create());

  const pkcs12 = (algorithm: 'aes256' | '3des'): Uint8Array =>
    fromBinary(
      forge.asn1
        .toDer(
          forge.pkcs12.toPkcs12Asn1(privateKey, [certificate], password, {
            algorithm,
            generateLocalKeyId: true,
          }),
        )
        .getBytes(),
    );

  return {
    modern: pkcs12('aes256'),
    legacy: pkcs12('3des'),
    pem: forge.pki.privateKeyToPem(privateKey) + forge.pki.certificateToPem(certificate),
    certificateOnlyPem: forge.pki.certificateToPem(certificate),
    password,
    commonName,
  };
}
